--DROP TAble "bridgeAttributeDataObject";

CREATE TABLE "bridgeAttributeDataObject" 
("DataObjectLabel" text,
"dcdtr:dataObject" text,
"AttributeLabel" text,
"dcdtr:element" text,
"cardinality" text,
"sequence" text,
"encoding" text,
"nilable" text);

ALTER TABLE "bridgeAttributeDataObject" OWNER TO grg_dba;

INSERT INTO "bridgeAttributeDataObject" 
("DataObjectLabel", "dcdtr:dataObject", "AttributeLabel", "dcdtr:element", "cardinality", "sequence", "encoding", "nilable")

VALUES

('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Facility URI', 'class/attribute/facilityuri', '1', '2', 'string 255', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Plant Name', 'class/attribute/plantname', '1', '3', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Plant Type', 'class/attribute/planttype', '1', '4', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Other Feature ID', 'class/attribute/otherfeatureid', '0..1', '5', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Label', 'class/attribute/label', '1', '6', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Owner', 'class/attribute/owner', '1', '7', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Operator', 'class/attribute/operator', '0..1', '8', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Operational Date', 'class/attribute/operationaldate', '1', '9', 'xs:dateTime', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Status', 'class/attribute/status', '1', '10', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Status Date', 'class/attribute/statusdate', '0..1', '11', 'xs:dateTime', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'PLSS Location', 'class/attribute/plssmeridians', '0..1', '12', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Township', 'class/attribute/township', '0..1', '13', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Range', 'class/attribute/range', '0..1', '14', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Section ', 'class/attribute/section-', '0..1', '15', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Section Part', 'class/attribute/sectionpart', '0..1', '16', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'UTM Datum Zone', 'class/attribute/utme', '0..1', '17', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'UTM E', 'class/attribute/utmn', '0..1', '18', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'UTM Datum Zone', 'class/attribute/utmdatumzone', '0..1', '19', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'County', 'class/attribute/county', '1', '20', 'xs:sting', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'State', 'class/attribute/state', '1', '21', 'xs:sting', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Latitude Correction mgal', 'class/attribute/latitudedegree', '1', '22', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Longitude Degree', 'class/attribute/longitudedegree', '1', '23', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'SRS', 'class/attribute/srs', '1', '24', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '1', '25', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Location Uncertainty Code', 'class/attribute/locationuncertaintycode', '0..1', '26', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Location Uncertainty Radius', 'class/attribute/locationuncertaintyradius', '0..1', '27', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Location Keyword', 'class/attribute/locationkeyword', '0..1', '28', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Notes', 'class/attribute/notes', '1', '29', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Use Application', 'class/attribute/useapplication', '1', '30', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Capacity MW', 'class/attribute/capacity-mw', '1', '31', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Event URI', 'class/attribute/facilitycontactname', '1', '32', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Facility Postal Address', 'class/attribute/facilitypostaladdress', '0..1', '33', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Facility Name', 'class/attribute/facility-ostalzipcode', '0..1', '34', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Event URI', 'class/attribute/facilitycontactphone', '0..1', '35', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Event URI', 'class/attribute/facilitycontactemailaddress', '0..1', '36', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Source', 'class/attribute/source', '1', '37', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Fluid Temperature Centigrade', 'class/attribute/fluidtemperature-c', '0..1', '38', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Flow gpm', 'class/attribute/flow-gpm', '0..1', '39', 'xs:double', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Related Resource', 'class/attribute/relatedresource', '0..1', '40', 'xs:string', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'MetadataURI', 'class/attribute/metadatauri', '0..1', '41', 'string-255', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Update Time Stamp', 'class/attribute/updatetimestamp', '1', '42', 'xs:dateTime', ''),
('Geothermal Power Plant Occurrence', 'class/data-object/geothermal-power-plant-occurrence', 'Geographic Position', 'class/attribute/geographicposition', '1', '43', 'gml:PointPropertyType', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Plant Production Stat URI', 'class/attribute/plant-productionstaturi', '1', '2', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Plant Production Stat Label', 'class/attribute/plant-productionstatlabel', '1', '3', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Power Plant Facility URI', 'class/attribute/powerplantfacilityuri', '1', '4', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Plant Name', 'class/attribute/plantname', '1', '5', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Other Feature ID', 'class/attribute/otherfeatureid', '0..1', '6', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Notes', 'class/attribute/notes', '0..1', '7', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Plant Type', 'class/attribute/planttype', '1', '8', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Year Commissioned', 'class/attribute/yearcommissioned', '0..1', '9', 'xs:dateTime', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'UTM Datum Zone', 'class/attribute/utme', '0..1', '10', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'UTM E', 'class/attribute/utmn', '0..1', '11', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'UTM Datum Zone', 'class/attribute/utmdatumzone', '0..1', '12', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Postal Address', 'class/attribute/postaladdress', '0..1', '13', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'County', 'class/attribute/county', '1', '14', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'State', 'class/attribute/state', '1', '15', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Latitude Correction mgal', 'class/attribute/latitudedegree', '1', '16', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Longitude Degree', 'class/attribute/longitudedegree', '1', '17', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'SRS', 'class/attribute/srs', '1', '18', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '0..1', '19', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Reporting Period', 'class/attribute/reportingperiod', '1', '20', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Start Report Interval', 'class/attribute/startreportinterval', '1', '21', 'xs:dateTime', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'End Report Interval', 'class/attribute/endreportinterval', '1', '22', 'xs:dateTime', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Report Year', 'class/attribute/reportyear', '1', '23', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Capacity MW', 'class/attribute/capacity-mw', '0..1', '24', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Gross Production MWhr', 'class/attribute/grossproduction-mwhr', '0..1', '25', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Net Production MWhr', 'class/attribute/netproduction-mwhr', '0..1', '26', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Average Price cents per kilowatt-hour.', 'class/attribute/averageprice-c-kw-h', '0..1', '27', 'xs:double', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Related Resource', 'class/attribute/relatedresource', '0..1', '28', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'MetadataURI', 'class/attribute/metadatauri', '0..1', '29', 'xs:string', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Update Time Stamp', 'class/attribute/updatetimestamp', '1', '30', 'xs:dateTime', ''),
('Power Plant Production Result', 'class/data-object/power-plant-production-result', 'Geographic Position', 'class/attribute/geographicposition', '1', '31', 'gml:PointPropertyType', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Other Feature ID', 'class/attribute/otherfeatureid', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Depth Top Interval ft', 'class/attribute/depthtopinterval-ft', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Depth Bottom Interval ft', 'class/attribute/depthbottominterval-ft', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Permeability, Intrinsic mD', 'class/attribute/permeabilityintrinsic-md', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'porosity mean pct', 'class/attribute/porositymean-pct', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Cementation factor', 'class/attribute/cementationfactor', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Water Resistivity ohm/m', 'class/attribute/resistivitywater-ohm-m', '0..1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Formation Factor', 'class/attribute/formationfactor', '0..1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Lithology', 'class/attribute/lithology', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Formation Name', 'class/attribute/formationname', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Notes', 'class/attribute/notes', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Well Name', 'class/attribute/wellname', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Zip', 'classclass/attribute/plsslocation', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'County', 'class/attribute/county', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/wsp2321data', 'Source', 'class/attribute/source', '1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Sampling Feature URI', 'class/attribute/samplingfeatureuri', '1', '', 'Excel:General', 'TRUE'),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Lithology Description', 'class/attribute/lithologydescription', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Formation Name', 'class/attribute/formationname', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Formation Name', 'class/attribute/formationname', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Notes', 'class/attribute/notes', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Observed Property Name', 'class/attribute/observedpropertyname', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Observed Numeric Value minimum', 'class/attribute/observednumericvalueminimum', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Observed Numeric Value maximum', 'class/attribute/observednumericvaluemaximum', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Observed Numeric Value', 'class/attribute/observednumericvalue', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Standard Deviation', 'class/attribute/standarddeviation', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Measurement Count', 'class/attribute/measurementcount', '0..1', '', 'Excel:Number', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Measurement Procedure', 'class/attribute/measurementprocedure', '0..1', '', 'Excel:General', ''),
('Coordinate Location', 'class/data-object/cphydroobservationdata', 'Source', 'class/attribute/source', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Sampling Feature URI', 'class/attribute/samplingfeatureuri', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Latitude Correction mgal', 'class/attribute/latitude-degree', '1', '', 'Excel:Number', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Longitude Degree', 'class/attribute/longitude-degree', '1', '', 'Excel:Number', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Sampling Feature Type', 'class/attribute/samplingfeaturetype', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Formation Name', 'class/attribute/formationname', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Formation Name', 'class/attribute/formationname', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Lithology', 'class/attribute/lithology', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Observed Property Name', 'class/attribute/observedpropertyname', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Observed Numeric Value', 'class/attribute/observednumericvalue', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Depth Top Interval ft', 'class/attribute/depthtopinterval-ft', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Depth Bottom Interval ft', 'class/attribute/depthbottominterval-ft', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Measurement Procedure', 'class/attribute/measurementprocedure', '1', '', 'Excel:General', ''),
('WeigelObservation', 'class/data-object/weigelobservation', 'Source', 'class/attribute/source', '1', '', 'Excel:General', ''),
('Quantity with units', 'class/data-object/well-test-result', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Observation URI', 'class/attribute/observationuri', '1', '2', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Well Header URI', 'class/attribute/wellheaderuri', '1', '3', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Well Name', 'class/attribute/wellname', '0?1', '4', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'API No', 'class/attribute/apino', '0..1', '5', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Label', 'class/attribute/label', '1', '6', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Other ID', 'class/attribute/otherid', '0?1', '7', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Test Name', 'class/attribute/testname', '1', '8', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Test Type', 'class/attribute/testtype', '1', '9', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Test Type Description', 'class/attribute/testtypedescription', '0?1', '10', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Test Operator', 'class/attribute/testoperator', '0..1', '11', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Test date time', 'class/attribute/testdatetime', '0..1', '12', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Test Number', 'class/attribute/testnumber', '0..1', '13', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Field', 'class/attribute/field', '0..1', '14', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'County', 'class/attribute/county', '1', '15', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'State', 'class/attribute/state', '1', '16', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'PLSS Meridians', 'class/attribute/plss-meridians', '0..1', '17', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'TWP', 'class/attribute/twp', '0..1', '18', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'RGE', 'class/attribute/rge', '0..1', '19', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Section ', 'class/attribute/section-', '0..1', '20', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Section Part', 'class/attribute/sectionpart', '0..1', '21', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Parcel', 'class/attribute/parcel', '0..1', '22', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'UTM E', 'class/attribute/utm-e', '0..1', '23', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'UTM N', 'class/attribute/utm-n', '0..1', '24', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'UTM Datum Zone', 'class/attribute/utmdatumzone', '0..1', '25', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Latitude Degrees', 'class/attribute/latdegree', '1', '26', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Longitude Degree', 'class/attribute/longdegree', '1', '27', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'SRS', 'class/attribute/srs', '1', '28', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '1', '29', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Target Formation', 'class/attribute/targetformation', '1', '30', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Target Feature URI', 'class/attribute/targetfeatureuri', '0..1', '31', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Depth Top Open Zone', 'class/attribute/depthtopopenzone', '1', '32', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Elevation Top Open Zone msl', 'class/attribute/elevationtopopenzone-msl', '0..1', '33', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Depth Bottom Open Zone', 'class/attribute/depthbottomopenzone', '1', '34', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Elevation Bottom Open Zone msl', 'class/attribute/elevationbottomopenzone-msl', '0..1', '35', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Units Of Measure', 'class/attribute/unitsofmeasure', '1', '36', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Depth Reference Point', 'class/attribute/depthreferencepoint', '0..1', '37', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Formation TD', 'class/attribute/formationtd', '0..1', '38', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Hole Diameter in', 'class/attribute/holediameter-in', '0..1', '39', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Drill Pipe Length', 'class/attribute/drillpipelength', '0..1', '40', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Drill Pipe Internal Diameter in', 'class/attribute/drillpipeinternaldiameter-in', '0..1', '41', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Flow History', 'class/attribute/flowhistory', '1', '42', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Pressure Initial Shut In', 'class/attribute/pressureinitialshutin', '1', '43', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Time Initial Shut In min', 'class/attribute/timeinitialshutin-min', '1', '44', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Preferred Pressure', 'class/attribute/preferredpressure', '1', '45', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Pressure Final Shut In', 'class/attribute/pressurefinalshutin', '1', '46', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Time Final Shut In min', 'class/attribute/timefinalshutin-min', '1', '47', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Shut In Pressure Method', 'class/attribute/shutinpressuremethod', '0..1', '48', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Pressure units', 'class/attribute/units-pressure', '1', '49', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Hydrostatic Pressure', 'class/attribute/hydrostaticpressure', '1', '50', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Hydrostatic Pressure Method', 'class/attribute/hydrostaticpressuremethod', '1', '51', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Equilibrium Pressure', 'class/attribute/equilibriumpressure', '0..1', '52', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Equilibrium Pressure Method', 'class/attribute/equilibriumpressuremethod', '0..1', '53', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Flow Pressure Min', 'class/attribute/flowpressuremin', '0..1', '54', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Flow Pressure Max', 'class/attribute/flowpressuremax', '0..1', '55', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Flow Pressure Method', 'class/attribute/flowpressuremethod', '0..1', '56', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Test Fluid', 'class/attribute/testfluid', '0..1', '57', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Formation Temperature', 'class/attribute/formationtemperature', '0..1', '58', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Temperature Correction', 'class/attribute/temperaturecorrection', '0..1', '59', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Temperature Flowing', 'class/attribute/temperatureflowing', '0..1', '60', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Temperature units', 'class/attribute/units-temperature', '0..1', '61', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Related Resource', 'class/attribute/relatedresource', '0..1', '62', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Source', 'class/attribute/source', '1', '63', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Notes', 'class/attribute/notes', '0..1', '64', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-test-result', 'Shape', 'class/attribute/shape', '1', '65', 'gml:PointPropertyType', ''),
('Quantity with units', 'class/data-object/well-log-result', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Log URI', 'class/attribute/loguri', '1', '2', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Other Log ID', 'class/attribute/otherlogid', '0..1', '3', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Display Name', 'class/attribute/displayname', '1', '4', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Notes', 'class/attribute/notes', '0..1', '5', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Log Type Term', 'class/attribute/logtypeterm', '1', '6', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Log Type Name', 'class/attribute/logtypename', '0..1', '7', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'WellBore URI', 'class/attribute/wellboreuri', '1', '8', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'WellBore Name ', 'class/attribute/wellborename', '0..1', '9', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'API No', 'class/attribute/apino', '0..1', '10', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Parent Well URI', 'class/attribute/parentwelluri', '0..1', '11', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Keywords', 'class/attribute/keywords', '0..1', '12', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Spud Date', 'class/attribute/spuddate', '0..1', '13', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Well Type', 'class/attribute/welltype', '1', '14', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Status', 'class/attribute/status', '0..1', '15', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Commodity Of Interest', 'class/attribute/commodityofinterest', '0..1', '16', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Status Date', 'class/attribute/statusdate', '0..1', '17', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Function', 'class/attribute/function', '0..1', '18', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Production status', 'class/attribute/production', '0..1', '19', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Producing Interval ', 'class/attribute/producinginterval', '0..1', '20', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'County', 'class/attribute/county', '1', '21', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'State', 'class/attribute/state', '1', '22', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Field', 'class/attribute/field', '0..1', '23', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Other Location Name', 'class/attribute/otherlocationname', '0..1', '24', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'PLSS Meridians', 'class/attribute/plss-meridians', '0..1', '25', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'TWP', 'class/attribute/twp', '0..1', '26', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'RGE', 'class/attribute/rge', '0..1', '27', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Section ', 'class/attribute/section-', '0..1', '28', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Section Part', 'class/attribute/sectionpart', '0..1', '29', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Parcel', 'class/attribute/parcel', '0..1', '30', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Latitude Degrees', 'class/attribute/latdegree', '1', '31', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Longitude Degree', 'class/attribute/longdegree', '1', '32', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-log-result', 'SRS', 'class/attribute/srs', '1', '33', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '1', '34', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Driller Total Depth ft', 'class/attribute/drillertotaldepth-ft', '1', '35', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Well Bore Shape', 'class/attribute/wellboreshape', '0..1', '36', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Elevation  Ground Level feet', 'class/attribute/elevationgl-ft', '1', '37', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Top Logged Interval ft', 'class/attribute/toploggedinterval-ft', '1', '38', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Bottom Logged Interval ft', 'class/attribute/bottomloggedinterval-ft', '1', '39', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Date Time Log Run', 'class/attribute/datetimelogrun', '1', '40', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Paper Copy Location', 'class/attribute/papercopylocation', '0..1', '41', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'ScannedFileURL', 'class/attribute/scannedfileurl', '0..1', '42', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'LASFileURL', 'class/attribute/lasfileurl', '0..1', '43', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Other Distribution', 'class/attribute/otherdistribution', '0..1', '44', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Related Resource', 'class/attribute/relatedresource', '0..1', '45', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Source', 'class/attribute/source', '1', '46', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-log-result', 'Shape', 'class/attribute/shape', '1', '47', 'gml:PointPropertyType', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Header URI', 'class/attribute/headeruri', '1', '2', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Well Name', 'class/attribute/wellname', '0..1', '3', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'API No', 'class/attribute/apino', '0..1', '4', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Label', 'class/attribute/label', '1', '5', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Other ID', 'class/attribute/otherid', '0..1', '6', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Other Name', 'class/attribute/othername', '0..1', '7', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Borehole Name', 'class/attribute/boreholename', '0..1', '8', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Parent Well URI', 'class/attribute/parentwelluri', '0..1', '9', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Operator', 'class/attribute/operator', '0..1', '10', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Mineral Owner', 'class/attribute/mineralowner', '0..1', '11', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Driller', 'class/attribute/driller', '0..1', '12', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Lease Name', 'class/attribute/leasename', '0..1', '13', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Spud Date', 'class/attribute/spuddate', '0..1', '14', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Ended Drilling Date', 'class/attribute/endeddrillingdate', '0..1', '15', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Drilling Method', 'class/attribute/drillingmethod', '0..1', '16', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Well Type', 'class/attribute/welltype', '0..1', '17', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Status', 'class/attribute/status', '0..1', '18', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Commodity Of Interest', 'class/attribute/commodityofinterest', '0..1', '19', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Status Date', 'class/attribute/statusdate', '0..1', '20', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Function', 'class/attribute/function', '0..1', '21', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Production status', 'class/attribute/production', '0..1', '22', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Producing Interval ', 'class/attribute/producinginterval', '0..1', '23', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Release Date', 'class/attribute/releasedate', '0..1', '24', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'County', 'class/attribute/county', '1', '25', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'State', 'class/attribute/state', '1', '26', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Field', 'class/attribute/field', '0..1', '27', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Other Location Name', 'class/attribute/otherlocationname', '0..1', '28', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'PLSS Meridians', 'class/attribute/plss-meridians', '0..1', '29', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'TWP', 'class/attribute/twp', '0..1', '30', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'RGE', 'class/attribute/rge', '0..1', '31', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Section ', 'class/attribute/section-', '0..1', '32', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Section Part', 'class/attribute/sectionpart', '0..1', '33', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Parcel', 'class/attribute/parcel', '0..1', '34', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'UTM E', 'class/attribute/utm-e', '0..1', '35', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'UTM N', 'class/attribute/utm-n', '0..1', '36', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'UTM Datum Zone', 'class/attribute/utmdatumzone', '0..1', '37', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Latitude Degrees', 'class/attribute/latdegree', '1', '38', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Longitude Degree', 'class/attribute/longdegree', '1', '39', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'SRS', 'class/attribute/srs', '1', '40', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '1', '41', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Location Uncertainty Code', 'class/attribute/locationuncertaintycode', '0..1', '42', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Location Uncertainty Radius', 'class/attribute/locationuncertaintyradius', '0..1', '43', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Driller Total Depth', 'class/attribute/drillertotaldepth', '0..1', '44', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Depth Reference Point', 'class/attribute/depthreferencepoint', '0..1', '45', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Length Units', 'class/attribute/lengthunits', '0..1', '46', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Well Bore Shape', 'class/attribute/wellboreshape', '0..1', '47', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'True Vertical Depth', 'class/attribute/trueverticaldepth', '0..1', '48', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Elevation KB', 'class/attribute/elevationkb', '0..1', '49', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Elevation DF', 'class/attribute/elevationdf', '0..1', '50', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Elevation GL', 'class/attribute/elevationgl', '0..1', '51', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Formation TD', 'class/attribute/formationtd', '0..1', '52', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Bit Diameter at Collar', 'class/attribute/bitdiametercollar', '0..1', '53', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Bit Diameter at TD', 'class/attribute/bitdiametertd', '0..1', '54', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Diameter Units', 'class/attribute/diameterunits', '0..1', '55', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Related Resource', 'class/attribute/relatedresource', '0..1', '56', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Notes', 'class/attribute/notes', '0..1', '57', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Casing Logger', 'class/attribute/casinglogger', '0..1', '58', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Casing Bottom Depth Driller', 'class/attribute/casingbottomdepthdriller', '0..1', '59', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Casing Top Depth', 'class/attribute/casingtopdepth', '0..1', '60', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Casing Pipe Diameter', 'class/attribute/casingpipediameter', '0..1', '61', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Casing Weight', 'class/attribute/casingweight', '0..1', '62', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Casing Weight Units', 'class/attribute/casingweightunits', '0..1', '63', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Casing Thickness', 'class/attribute/casingthickness', '0..1', '64', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Information Source', 'class/attribute/informationsource', '1', '65', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-header-occurrence', 'Shape', 'class/attribute/shape', '1', '66', 'gml:PointPropertyType', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Observation URI', 'class/attribute/observationuri', '1', '2', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Record Name', 'class/attribute/recordname', '1', '3', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Notes', 'class/attribute/notes', '0..1', '4', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Operator', 'class/attribute/operator', '0..1', '5', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Producing Feature', 'class/attribute/producingfeature', '0..1', '6', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Header URI', 'class/attribute/headeruri', '1', '7', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Well Name', 'class/attribute/wellname', '1', '8', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'API No', 'class/attribute/apino', '0..1', '9', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Other ID', 'class/attribute/otherid', '0..1', '10', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'County', 'class/attribute/county', '1', '11', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'State', 'class/attribute/state', '1', '12', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Field', 'class/attribute/field', '0..1', '13', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Other Location Name', 'class/attribute/otherlocationname', '0..1', '14', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Latitude Degrees', 'class/attribute/latdegree', '1', '15', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Longitude Degree', 'class/attribute/longdegree', '1', '16', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'SRS', 'class/attribute/srs', '1', '17', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '1', '18', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Interval Start Date Time', 'class/attribute/intervalstartdatetime', '1', '19', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Interval End Date Time', 'class/attribute/intervalenddatetime', '1', '20', 'xs:dateTime', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Duration Days', 'class/attribute/durationdays', '1', '21', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Permit', 'class/attribute/permit', '0..1', '22', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Fluid Type', 'class/attribute/fluidtype', '1', '23', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Fluid Volume', 'class/attribute/fluidvolume', '1', '24', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Fluid Volume Units', 'class/attribute/fluidvolumeunits', '1', '25', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Temperature Fahrenheit', 'class/attribute/temperature-f', '1', '26', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Pressure psi', 'class/attribute/pressure-psi', '1', '27', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Aggregation Type', 'class/attribute/aggregationtype', '1', '28', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Measurement Method', 'class/attribute/measurementmethod', '1', '29', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Contact Interval Top', 'class/attribute/contactintervaltop', '0..1', '30', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Contact Interval Bottom', 'class/attribute/contactintervalbottom', '0..1', '31', 'xs:double', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Source', 'class/attribute/source', '1', '32', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'MetadataURI', 'class/attribute/metadatauri', '0..1', '33', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Related Resources', 'class/attribute/relatedresources', '0..1', '34', 'xs:string', ''),
('Quantity with units', 'class/data-object/well-fluid-production-result', 'Shape', 'class/attribute/shape', '1', '35', 'gml:PointPropertyType', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Feature URI', 'class/attribute/featureuri', '1', '2', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Volc Vent Name', 'class/attribute/volcventname', '1', '3', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Label', 'class/attribute/label', '1', '4', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Map Label', 'class/attribute/maplabel', '1', '5', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Description', 'class/attribute/description', '0..1', '6', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Feature Type', 'class/attribute/featuretype', '1', '7', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Volcanic Group', 'class/attribute/volcanicgroup', '0..1', '8', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'UTM E', 'class/attribute/utm-e', '0..1', '9', 'xs:double', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'UTM N', 'class/attribute/utm-n', '0..1', '10', 'xs:double', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'UTM Datum Zone', 'class/attribute/utmdatumzone', '0..1', '11', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Latitude Degrees', 'class/attribute/latdegree', '1', '12', 'xs:double', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Longitude Degree', 'class/attribute/longdegree', '1', '13', 'xs:double', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'SRS', 'class/attribute/srs', '1', '14', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '1', '15', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'County', 'class/attribute/county', '1', '16', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'State', 'class/attribute/state', '1', '17', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Location Keyword', 'class/attribute/locationkeyword', '0..1', '18', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Vent Elevation', 'class/attribute/ventelevation', '1', '19', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Elevation Units of Measure', 'class/attribute/elevationuom', '1', '20', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Related Feature', 'class/attribute/relatedfeature', '0..1', '21', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Geologic History', 'class/attribute/geologichistory', '1', '22', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Youngest Age', 'class/attribute/youngestage', '0..1', '23', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Oldest Age', 'class/attribute/oldestage', '0..1', '24', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Youngest Radiometric Age Ma', 'class/attribute/youngestradiometricage-ma', '0..1', '25', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Oldest Radiometric Age Ma', 'class/attribute/oldestradiometricage-ma', '0..1', '26', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Age Uncertainty Ma', 'class/attribute/ageuncertainty-ma', '0..1', '27', 'xs:double', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Age Source', 'class/attribute/agesource', '0..1', '28', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Geologic Unit', 'class/attribute/geologicunit', '0..1', '29', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Material Composition', 'class/attribute/materialcomposition', '0..1', '30', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'FlowType', 'class/attribute/flowtype', '0..1', '31', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Notes', 'class/attribute/notes', '0..1', '32', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Source', 'class/attribute/source', '1', '33', 'xs:string', ''),
('Volcanic Vent Occurrence', 'class/data-object/volcanic-vent-occurrence', 'Shape', 'class/attribute/shape', '1', '34', 'gml:PointPropertyType', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'OBJECTID', 'class/attribute/objectid', '1', '1', 'xs:int', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Thermal Spring URI', 'class/attribute/thermalspringuri', '1', '2', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Spring Name', 'class/attribute/springname', '1', '3', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Label', 'class/attribute/label', '0..1', '4', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Other Name', 'class/attribute/othername', '0..1', '5', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Other Identifier', 'class/attribute/otheridentifier', '0..1', '6', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Description', 'class/attribute/description', '0..1', '7', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Source', 'class/attribute/source', '1', '8', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Source URI', 'class/attribute/sourceuri', '0..1', '9', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Feature Type', 'class/attribute/featuretype', '1', '10', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Land Lease Owner', 'class/attribute/landleaseowner', '0..1', '11', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Other Location Name', 'class/attribute/otherlocationname', '0..1', '12', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'County', 'class/attribute/county', '1', '13', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'State', 'class/attribute/state', '1', '14', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'PLSS Meridians', 'class/attribute/plss-meridians', '0..1', '15', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Township', 'class/attribute/township', '0..1', '16', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Range', 'class/attribute/range', '0..1', '17', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Section ', 'class/attribute/section-', '0..1', '18', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Section Part', 'class/attribute/sectionpart', '0..1', '19', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Parcel', 'class/attribute/parcel', '0..1', '20', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'UTM E', 'class/attribute/utm-e', '0..1', '21', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'UTM N', 'class/attribute/utm-n', '0..1', '22', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'UTM Datum Zone', 'class/attribute/utmdatumzone', '0..1', '23', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Latitude Degrees', 'class/attribute/latdegree', '1', '24', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Longitude Degree', 'class/attribute/longdegree', '1', '25', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'SRS', 'class/attribute/srs', '1', '26', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Location Uncertainty Statement', 'class/attribute/locationuncertaintystatement', '1', '27', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Temperature', 'class/attribute/temperature', '1', '28', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Temperature Units', 'class/attribute/temperatureunits', '1', '29', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Temp Measurement Procedure', 'class/attribute/tempmeasurementprocedure', '1', '30', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Temp Measurement Date Time', 'class/attribute/tempmeasurementdatetime', '1', '31', 'xs:dateTime', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Flow', 'class/attribute/flow', '0..1', '32', 'xs:double', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Flow Units', 'class/attribute/flowunits', '0..1', '33', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Flow Measurement Procedure', 'class/attribute/flowmeasurementprocedure', '0..1', '34', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Flow Measurement Date Time', 'class/attribute/flowmeasurementdatetime', '0..1', '35', 'xs:dateTime', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Measurement Source', 'class/attribute/measurementsource', '1', '36', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Flow Continuity', 'class/attribute/flowcontinuity', '0..1', '37', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Classification', 'class/attribute/classification', '0..1', '38', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Related Water Chemistry', 'class/attribute/relatedwaterchemistry', '0..1', '39', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Related Resources', 'class/attribute/relatedresources', '0..1', '40', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Remarks', 'class/attribute/remarks', '0..1', '41', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Notes', 'class/attribute/notes', '0..1', '42', 'xs:string', ''),
('Thermal Spring Occurrence', 'class/data-object/thermal-spring-occurrence', 'Shape', 'class/attribute/shape', '1', '43', 'gml:PointPropertyType', '');
