DROP TABLE "Property";

CREATE TABLE "Property"
("URI" text,
"skos:prefLabel" text, 
"skos:altLabel" text, 
"dct:description" text, 
"skos:broader" text, 
"dcdtr:quantityKind" text, 
"dcdtr:componentContainerObject" text,
"comments" text,
  CONSTRAINT "Property_pkey" PRIMARY KEY ("URI")
)
WITH (
  OIDS=TRUE
);
ALTER TABLE public."Property"
  OWNER TO grg_dba;
GRANT ALL ON TABLE public."Property" TO grg_dba;
GRANT ALL ON TABLE public."Property" TO public;

INSERT INTO "Property" ("URI", 
"skos:prefLabel", 
"skos:altLabel", 
"dct:description",
"skos:broader",
"dcdtr:quantityKind", 
"dcdtr:componentContainerObject", 
"comments")
VALUES
('def/property/access-link', 'Access Link', '', 'URL or -live link- that will retrieve a digital file containing a scanned image of the log file on the World Wide Web.   Multiple locations may be listed, delimited by -|-.', '', '', '', ''),
('def/property/acidity', 'acidity', '', 'measure of the activity of hydrogen in some reagent', '', '', '', ''),
('def/property/administrative-position-name', 'Administrative Position Name', '', 'The name or title assigned to an adminstrtive position in a business organization.', '', '', '', ''),
('def/property/age', 'Age', '', 'The magnitude of the time interval since the origination of some feature or event', '', '', '', ''),
('def/property/agent-identifier', 'Agent Identifier', '', 'Unique identifier for a agent; indended for machine designation of the feature', '', '', '', ''),
('def/property/agent-name', 'Agent Name', '', '', '', '', '', ''),
('def/property/agent-type', 'Agent type', '', 'value categorizes an agent accoring to some classification scheme', '', '', '', ''),
('def/property/air-permeability', 'Air permeability', '', 'A permeability value measured using air as the transport fluid.', '', '', '', ''),
('def/property/air-temperature', 'Air temperature', 'Air Temp | temperature, air', 'temperature of the atmosphere at some location', '', '', '', ''),
('def/property/analytical-procedure-metadata', 'Analytical Procedure Metadata', '', 'Unique identifier that identifies an analysis observation whose analyte values are the detection limits for each analyte. Ideally, the identifier is an http URI that will dereference to a known, useful representation of the feature. This identifier will be used to cross reference the feature to other information related to this feature. Unique identifier for each set of samples, each analyzed using the same method, technique and using the same equipment.', '', '', '', ''),
('def/property/aquifer-productivity', 'Aquifer Productivity', '', 'The volume of water an aquifer releases from or takes into storage per unit surface area of the aquifer per unit change in head. One of the physical properties that characterize the capacity of an aquifer to release groundwater (others are  Storativity (S), and specific yield (Sy)). see https://en.wikipedia.org/wiki/Specific_storage', '', '', '', ''),
('def/property/area', 'Area', '', 'the surface area subtended by an object viewed from a particular orientation, independent of location (more specific than extent)', '', '', '', ''),
('def/property/auto-id', 'Auto ID', '', 'an automatically generated identifier that is unique in some context (e.g. within a single table in a database)', '', '', '', ''),
('def/property/bleaching-event-present', 'Bleaching event present', '', '', '', '', '', ''),
('def/property/bleaching-extent', 'Bleaching extent', '', 'property that quantifies the ratio of bleached to unbleached coral', '', '', '', ''),
('def/property/bleaching-present', 'Bleaching present', '', 'boolean test, true if bleaching present and an observation location', '', '', 'Atmosphere state', ''),
('def/property/body-thickness', 'Body Thickness', '', 'thickness of a geologic body, e.g. reservoir, sedimentary depositr, formation', '', '', '', ''),
('def/property/borehole-casing-extent', 'Borehole Casing Extent', '', 'An extent in the linear reference system achored to a borehole trace', '', '', '', ''),
('def/property/borehole-casing-thickness', 'Borehole Casing Thickness', '', 'Thickness Casing pipe installed in the borehole. Units must be same as diameter units specified in this record. If multiple pipe thicknesses used, these should be separated by the pipe character -|-. ', '', '', '', ''),
('def/property/borehole-casing-weight', 'Borehole Casing Weight', '', 'Casing pipe weight per length installed in the borehole.', '', '', '', ''),
('def/property/borehole-casing-weight-uom', 'Borehole Casing Weight UOM', '', 'Units for the reported Casing Weight: kg/m OR lbs/ft.', '', '', '', ''),
('def/property/borehole-collar-elevation', 'Borehole Collar Elevation', '', 'The elevation of the top of a well ', '', '', '', ''),
('def/property/borehole-spacing', 'Borehole Spacing', '', 'The average distance between boreholes in feet.', '', '', '', ''),
('def/property/capacity_mw', 'Capacity_MW', '', '', '', '', '', ''),
('def/property/category--name', 'Category  Name', '', 'Text string for human designation of a category', '', '', '', ''),
('def/property/cementation-factor', 'Cementation factor', 'cementation exponent', 'The cementation factor, m, of Archie-s equation has specific effects on electric conduction processes in porous media. It depends on the shape, type, and size of grains; the shape and size of pores and pore throats; and the size and number of dead-end pores. The dependence of m on the degree of cementation is not as strong as its dependence on the shape of grains and pores. (doi:10.1016/S0920-4105(99)00009-1).   The cementation exponent models how much the pore network increases the resistivity, as the rock itself is assumed to be non-conductive. If the pore network were to be modelled as a set of parallel capillary tubes, a cross-section area average of the rock-s resistivity would yield porosity dependence equivalent to a cementation exponent of 1. However, the tortuosity of the rock increases this to a higher number than 1. This relates the cementation exponent to the permeability of the rock, increasing permeability decreases the cementation exponent. The exponent m has been observed near 1.3 for unconsolidated sands, and is believed to increase with cementation. Common values for this cementation exponent for consolidated sandstones are 1.8 < m < 2.0. In carbonate rocks, the cementation exponent shows higher variance due to strong diagenetic affinity and complex pore structures. Values between 1.7 and 4.1 have been observed. The cementation exponent is usually assumed not to be dependent on temperature.  (https://en.wikipedia.org/wiki/Archie%27s_law)', '', '', '', ''),
('def/property/chemical-character', 'Chemical Character', '', 'a characteristic of a substance that is obeserved during a reaction', '', '', '', ''),
('def/property/chemical-composition', 'chemical composition', '', 'composition of a material described in terms of chemical constituents', '', '', '', ''),
('def/property/cloud-cover', 'Cloud cover', '', 'specification of the degree to which the sky is obscured by clouds.', '', '', '', ''),
('def/property/coloniality', 'Coloniality', '', 'of a coral colony. What exactly is the phenomenon?', '', '', '', ''),
('def/property/composition', 'Composition', '', 'the nature of something-s ingredients or constituents', '', '', '', ''),
('def/property/conductivity', 'Conductivity', '', '', '', '', '', ''),
('def/property/constituent-type', 'Constituent Type', '', '', '', '', '', ''),
('def/property/contact-information', 'Contact Information', '', 'Information that specifies an agent who should be contacted with questions or comments on a resoruce.', '', '', '', ''),
('def/property/contour-identifier', 'Contour Identifier', '', 'Unique identifier for a contour; indended for machine designation of the feature', '', '', '', ''),
('def/property/coordinate', 'Coordinate', '', 'The distance from the origin along one of the axes in a coordinate reference system', '', '', '', ''),
('def/property/coordinate-location', 'Coordinate Location', '', 'A location property specified with numeric coordinates within a coordinated based spatial reference system.', '', '', '', ''),
('def/property/coordinate-reference-system', 'Coordinate Reference System', '', 'A coordinate-based spatial reference system definition', '', '', '', ''),
('def/property/coral-mortality', 'Coral mortality', '', 'quantify the fraction of coral organisms that died during a reporting interval. ', '', '', '', ''),
('def/property/coral-recovery', 'Coral recovery', '', 'quantify the occurrence of healthy coral replacing coral that has been bleached', '', '', '', ''),
('def/property/corallite-part-axial', 'Corallite part axial', '', '', '', '', '', ''),
('def/property/correction', 'Correction', '', 'specification of a correction value applied to an observed value to account for some systematic error in measurement process', '', '', '', ''),
('def/property/count', 'Count', '', 'The total number of some entity instances', '', '', '', ''),
('def/property/coverage-domain-bound', 'Coverage Domain Bound', '', 'Depth to the bottom of the interval being tested.', '', '', '', ''),
('def/property/curation-location', 'Curation Location', '', 'Free text location name specifying an institution, museum, repository, or other facility where the sample is currently stored.', '', '', '', ''),
('def/property/customer', 'Customer', '', 'a person or organization that buys goods or services from a store or business.', '', '', '', ''),
('def/property/data-history', 'Data History', '', 'specification of the sequence of events that resulted in the current state of a data item', '', '', '', ''),
('def/property/datum-type', 'Datum Type', '', 'Specify where value in elevation field refers to.', '', '', '', ''),
('def/property/density', 'Density', '', 'mass divided by volume', '', '', '', ''),
('def/property/depth', 'depth', '', 'linear distance from a datum (typically the earth Surface) measured positive downward.', '', '', '', ''),
('def/property/description', 'Description', '', 'An information object that characterizes a resource. Generally understood to be text intended for humans.', '', '', '', ''),
('def/property/designation', 'Designation', '', 'A symbol understood by users to represent some other resource; identifier is a designation intended for machines, names and icons are intended for human users.', '', '', '', ''),
('def/property/diameter', 'Diameter', '', 'the length across a broadly circular shape profile, measured along a line passing through the center of the profile.', '', '', '', ''),
('def/property/displacement', 'Displacement', '', 'the distance two points have been moved relative to each other; has magnitude and direction components, and full specification should identify the offset points.', '', '', '', ''),
('def/property/distance', 'distance', '', 'distance between two places', '', '', '', ''),
('def/property/documentation', 'Documentation', '', 'Information describing a resource', '', '', '', ''),
('def/property/drilling-method', 'Drilling Method', '', 'Basic drilling technology used in the creation of the borehole. Separate multiple drilling methods with the pipe  -|- character.', '', '', '', ''),
('def/property/duration', 'Duration', '', 'the length of the time interval during which some thing continues, measure with units of time (seconds, days, years…)', '', '', '', ''),
('def/property/earth-resource-type', 'Earth Resource Type', '', 'specification of the kind of economic resource derived from the Earth', '', '', '', ''),
('def/property/elevation', 'Elevation', '', 'The linear distance above or below a horizontal reference surface (datum)', '', '', '', ''),
('def/property/elevation-datum', 'Elevation Datum', '', 'A horizontal reference surface from which elevations are measured', '', '', '', ''),
('def/property/e-mail-address', 'E-Mail Address', '', 'A URI that identifies a mailbox (message delivery endpoint) on the internet.', '', '', '', ''),
('def/property/energy', 'Energy', '', 'power derived from the utilization of physical or chemical resources', '', '', '', ''),
('def/property/eruptive-style-type', 'Eruptive Style Type', '', 'Term describing eruptive style', '', '', '', ''),
('def/property/event-date', 'Event date', '', 'property that specifies the calendar date with or without clock time within the day.', '', '', 'Ocean state', 'phenom is temperature; subject is water body-ocean-surface'),
('def/property/event-in-history', 'Event in History', '', 'an event in a history', '', '', 'Ocean state', 'phenom is temperature; subject is water body-ocean-bottom'),
('def/property/event-name', 'Event Name', '', 'Text string for human designation of an event', '', '', '', ''),
('def/property/event-type', 'Event Type', '', 'Event classification free text, according to classification scheme used by data provider. ', '', '', '', ''),
('def/property/extent', 'Extent', '', 'specification of the area or volume taken up by some thing; may be geolocated or not', '', '', '', ''),
('def/property/facility-contact', 'Facility Contact', '', 'specification of the agent that is the point of contact for information about or communication with a facility', '', '', '', ''),
('def/property/facility-name', 'Facility Name', '', 'Common or human-readable name by which the facility is known. Recommend using only web-safe characters (a-z A-Z 0-9 _-.) in the name. Be consistent in the naming ', '', '', '', ''),
('def/property/facility-operational-date', 'Facility Operational Date', '', 'Date on which a facility was made operational', '', '', '', ''),
('def/property/facility-operator', 'Facility Operator', '', 'the party responsible for operation of a facility', '', '', '', ''),
('def/property/facility-status', 'Facility Status', '', 'Term indicating the production status of the facility', '', '', '', ''),
('def/property/fault-boundary', 'Fault Boundary', '', 'vertical faults', '', '', '', ''),
('def/property/fault-count', 'Fault Count', '', 'Number of faults counted within some sampling extent.', '', '', '', ''),
('def/property/fault-movement-type', 'Fault Movement Type', '', 'Terms used to define the type of movement for a DisplacementValue on a ShearDisplacementStructure.', '', '', '', ''),
('def/property/feature-count', 'Feature Count', '', 'number of features counted within some sampling extent', '', '', '', ''),
('def/property/feature-description', 'Feature Description', '', 'Free text field for any additional observations or other information regarding the feature, any special considerations with this instance (quality, lithology, locality, size, weight, etc).', '', '', '', ''),
('def/property/feature-extent', 'Feature Extent', '', 'Specification of an extended (linear, area, or volume) location with respect to the Earth', '', '', '', ''),
('def/property/feature-history', 'Feature History', '', 'Description of the sequence of events leading to the current state of a feature', '', '', '', ''),
('def/property/feature-identifier', 'Feature Identifier', '', 'Unique identifier for a feature; indended for machine designation of the feature', '', '', 'date object', ''),
('def/property/feature-name', 'Feature Name', '', 'Text string for human designation of the feature', '', '', 'date object', ''),
('def/property/feature-of-interest', 'Feature of Interest', '', 'specifiction of the thing in the world that is the intended subject of an observation.', '', '', 'date object', ''),
('def/property/feature-type', 'Feature Type', '', 'Specification of a category to which the feature belongs', '', '', 'date time object', ''),
('def/property/fiat-geographic-area', 'Fiat Geographic Area', '', 'A cultural or administrative designation for a geographic extent, e.g. county, zip code area, fire district…', '', '', '', ''),
('def/property/fiat-geographic-position', 'Fiat Geographic Position', '', 'An arbitrarily named point location, like a street address;', '', '', '', ''),
('def/property/flow-continuity', 'Flow Continuity', '', 'Continuity of flow terms: Perennial water source (has continuous flow all year long); Intermittent (normally ceases flowing for weeks or months each year); ephermal (flow only for hours or days following rainfall).', '', '', '', ''),
('def/property/flow-direction', 'Flow Direction', '', 'Direction of fluid flow', '', '', '', ''),
('def/property/flow-velocity-magnitude', 'Flow Velocity Magnitude', '', 'Magnitude of the velocity of a flowing fluid (at some observation location)', '', '', '', ''),
('def/property/fluid-flow-rate', 'fluid flow rate', '', 'rate measure as volume per time for a fluid flowing in some conduit ', '', '', '', ''),
('def/property/fluid-flux', 'Fluid Flux', '', 'The rate of flow of a fluid per unit area, which has the dimensions [quantity]·[time]−1·[area]−1. This is general property which is actually measured as volume flux or mass flux, depending on whether the quantity is volume or mass.', '', '', '', ''),
('def/property/fluid-pressure', 'Fluid Pressure', '', '', '', '', '', ''),
('def/property/fluid-production', 'fluid production', '', 'volume of fluid produced by some facility', '', '', '', ''),
('def/property/fluid-quantity', 'Fluid Quantity', '', 'Fluid measure', '', '', '', ''),
('def/property/fluid-temperature', 'Fluid Temperature', '', 'The temperature of a fluid in some  sampling feature volume or location', '', '', '', ''),
('def/property/functional-characterization', 'Functional Characterization', '', 'property that specifies the function of a facility, instrument, or tool', '', '', '', ''),
('def/property/geospatial-coordinate-extent', 'Geospatial Coordinate Extent', '', 'Specification of an extended (linear, area, or volume) location with respect to the Earth that is represented with a set of geospatial coordinate positions defining the boundary of the extent', '', '', '', ''),
('def/property/geospatial-coordinate-position', 'Geospatial Coordinate Position', '', 'specification of a geospatial position using numeric coordinates within a spatial reference system.', '', '', '', ''),
('def/property/geospatial-extent', 'Geospatial Extent', '', 'Specification of an extended (linear, area, or volume) location with respect to the Earth', '', '', '', ''),
('def/property/geospatial-orientation', 'Geospatial Orientation', '', 'specification of the directional relationship between the geometry of some feature of interest and a spatial reference frame, e.g. the strike and dip of a plane, or the bearing of an outcrop trace.', '', '', '', ''),
('def/property/geospatial-position', 'Geospatial Position', '', 'Specification of the location of a point feature with respect to Earth, by coordinate or by name', '', '', '', ''),
('def/property/geospatial-x-coordinate', 'Geospatial X-coordinate', '', 'coordinate value along what is generally protrayed as the horizontal axis in a map view', '', '', '', ''),
('def/property/geospatial-y-coordinate', 'Geospatial Y-coordinate', '', 'coordinate value along what is generally protrayed as the vertical axis in a map view', '', '', '', ''),
('def/property/geothermal-resource-type', 'Geothermal Resource Type', '', 'Simple characterization of the geothermal resource.', '', '', '', ''),
('def/property/gravity-observation-correction', 'Gravity Observation Correction', '', 'Correction for variation of gravity with elevation due to the mass of the material between the gravity station and the vertical datum.  ', '', '', '', ''),
('def/property/gravity-observed-value', 'Gravity Observed Value', '', 'The measured value of the attraction of the earth-s mass for bodies near its surface', '', '', '', ''),
('def/property/ground-elevation', 'Ground Elevation', '', '', '', '', '', ''),
('def/property/heat-flow', 'Heat Flow', 'Heat flux density', 'the amount of heat transferred across a unit area in a unit time, ', '', '', '', ''),
('def/property/heat-flux', 'Heat Flux', 'Thermal flux', 'the rate of heat energy transfer through a given surface per unit time.', '', '', '', ''),
('def/property/heat-production', 'Heat Production', '', 'rate of heat production; units like ? Calories/hr, which is a unit of power.', '', '', '', ''),
('def/property/history', 'History', '', 'Description of the sequence of events leading to the current state of a resource', '', '', '', ''),
('def/property/hydraulic-conductivity', 'Hydraulic conductivity', '', 'The proportionality constant specifically for the flow of water through a porous media; permeability is a portion of this, and is a property of the porous media only, not the fluid. Given the value of hydraulic conductivity for a subsurface system, the permeability can be calculated.  in this case, reported as meters/sec', '', '', '', ''),
('def/property/hydraulic-transmissivity', 'Hydraulic Transmissivity', '', 'The transmissivity is a measure of how much water can be transmitted horizontally, such as to a pumping well. Transmissivity is directly proportional to horizontal hydraulic conductivity and thickness of the transmitting layer.', '', '', '', ''),
('def/property/hydrologic-setting', 'Hydrologic Setting', '', 'a notional location within a conceptual hydrologic environment, e.g. above-below water table.', '', '', '', ''),
('def/property/identifier', 'Identifier', '', 'A designation for a resoruce intended for machine use, but typically intelligible to human users as well.', '', '', '', ''),
('def/property/index-term', 'Index Term', '', 'a term that captures the essence of the topic', '', '', '', ''),
('def/property/individual-name', 'Individual Name', 'Person name', 'The name of an individual person', '', '', '', ''),
('def/property/information', 'Information', '', 'a property that provides information about a resource in an unconstratained way; typically implemented as free text.', '', '', '', ''),
('def/property/instrument-name', 'Instrument Name', '', 'Text string for human designation of an instrument', '', '', '', ''),
('def/property/instrument-type', 'instrument type', '', 'instrument or sensor type', '', '', '', ''),
('def/property/intrinsic-permeability', 'intrinsic permeability', '', 'Intrinsic permeability is permeability calculated an intensive property (not a spatial average of a heterogeneous block of material), i.e. a function of the material structure only (and not of the fluid) ', '', '', '', ''),
('def/property/label', 'Label', '', 'A short local name for an item for use in visualizations', '', '', '', ''),
('def/property/latitude', 'Latitude', '', '', '', '', '', ''),
('def/property/legal-permit', 'legal permit', '', 'specification of legal documentation authorizing some activity', '', '', '', ''),
('def/property/length', 'length', '', 'dimension of an object measure using some unit of length', '', '', '', ''),
('def/property/lithology-type', 'Lithology Type', '', 'specification of lithology using a category from some classification scheme', '', '', '', ''),
('def/property/local-identifier', 'Local Identifier', '', 'Unique identifier for a local feature; indended for machine designation of the feature', '', '', '', ''),
('def/property/local-permeability', 'Local permeability', '', 'permeabililty measured in a rock body by one of several pump tests in a well; intended to represent the rock volume in the local vicinity of the perforated part of the well bore', '', '', '', ''),
('def/property/location', 'Location', '', 'Specification of where some thing is relative to Earth; general concept. May be specified by name, or using some geospatial reference system. May be fiat, physiographic, or notional.', '', '', '', ''),
('def/property/location-name', 'Location Name', '', 'general concept for a property that specifies a particular location by name; may be a fiat location (arbitrarily defined by culture or government) or a named geographic feature (mountain, river, island…)', '', '', '', ''),
('def/property/location-uncertainty', 'Location Uncertainty', '', 'positional Accuracy', '', '', '', ''),
('def/property/location-uncertainty-code', 'Location Uncertainty Code', '', '', '', '', '', ''),
('def/property/longitude', 'Longitude', '', '', '', '', '', ''),
('def/property/market-proximity', 'Market Proximity', '', 'specification of the distance according to some metric between a resource and intended consumers of that resources', '', '', '', ''),
('def/property/mass', 'Mass', '', '', '', '', '', ''),
('def/property/mass-fluid-flux', 'Mass fluid flux', '', 'the volume of fluid that passes through a unit area per unit time', '', '', '', ''),
('def/property/material-type', 'Material Type', '', 'term classifying the material type', '', '', '', ''),
('def/property/measurement-count', 'Measurement Count', '', 'number of measurements or samples used to determine the value', '', '', '', ''),
('def/property/metadata-reference', 'Metadata Reference', '', 'a reference identifier that identifies a metadata information object.', '', '', '', ''),
('def/property/mineral-composition', 'mineral composition', '', 'Composition of a material described in terms of mineral constituents', '', '', '', ''),
('def/property/name', 'Name', '', 'Text string for human designation of a resource', '', '', '', ''),
('def/property/notes', 'Notes', '', 'additional unstructured information that provides useful information for understanding a data value', '', '', '', ''),
('def/property/notional-location', 'Notional Location', '', 'Specification of a resource location based on a categorization of location types, e.g. tectonic setting, depositional environment, geologic province.   [need to clarify distinction from feature type]', '', '', '', ''),
('def/property/object-shape', 'object Shape', '', 'specification of the shape of an object ', '', '', '', ''),
('def/property/observation-history', 'Observation History', '', 'Description of the sequence of events leading to the current state of a observation', '', '', '', ''),
('def/property/observation-identifier', 'Observation Identifier', '', 'Unique identifier for a observation; indended for machine designation of the feature', '', '', '', ''),
('def/property/observation-name', 'Observation Name', '', 'Text string for human designation of an observation', '', '', '', ''),
('def/property/observation-platform', 'Observation platform', 'Ship, vessel, satellite, tower', 'specification of the vehicle or instrumentation package that was used to acquire and observation. Platforms contain instruments, instruments contain sensors. Platform generally has connotation of a self-contained unit.', '', '', '', ''),
('def/property/observation-procedure', 'Observation Procedure', '', 'Text description of how the measurement was made', '', '', '', ''),
('def/property/observation-type', 'Observation Type', '', '', '', '', '', ''),
('def/property/observed-property', 'Observed Property', '', 'property of an observation that specifies the phenomenon quantified by the observation result', '', '', '', ''),
('def/property/observed-value', 'Observed Value', '', 'The result value of an observation', '', '', '', ''),
('def/property/observer-name', 'Observer name', '', 'the name of the person who made an observation', '', '', '', ''),
('def/property/older-age', 'Older Age', '', 'The older bound for the age of a feature.', '', '', '', ''),
('def/property/operational-date', 'Operational Date', '', '', '', '', '', ''),
('def/property/operator', 'Operator', '', '', '', '', '', ''),
('def/property/organism-abundance-global', 'Organism abundance global', '', '', '', '', '', ''),
('def/property/organism-abundance-regional', 'Organism abundance regional', '', '', '', '', '', ''),
('def/property/organism-age-maturity', 'Organism age maturity', '', 'age of organism at maturity', '', '', '', ''),
('def/property/organization-name', 'Organization Name', '', '', '', '', '', ''),
('def/property/orientation', 'Orientation', '', 'specification of the directional relationship between a feature and some spatial reference system (geographic or non-geographic)', '', '', '', ''),
('def/property/otherid', 'OtherID', '', '', '', '', '', ''),
('def/property/owner', 'Owner', '', '', '', '', '', ''),
('def/property/parent-feature-identifier', 'Parent Feature Identifier', '', 'Unique identifier for a parent feature; indended for machine designation of the feature', '', '', '', ''),
('def/property/periodicity', 'Periodicity', '', 'the quality or character of being periodic', '', '', '', ''),
('def/property/permeability', 'Permeability', '', 'the state or quality of a material or membrane that causes it to allow liquids or gases to pass through it. Permeability is the property of rocks that is an indication of the ability for fluids (gas or liquid) to flow through rocks; The SI unit for permeability is m2. A practical unit for permeability is the darcy (d), or more commonly the millidarcy (md) (1 darcy \approx10−12m2).', '', '', '', ''),
('def/property/physical-length-dimension', 'physical length dimension', '', 'specificaiton of the size of an object in terms of length measure along some axis of the object', '', '', '', ''),
('def/property/physiographic-feature', 'Physiographic feature', 'named landform', 'a location specified by a named landform, ideally should be with reference to some gazetteer authority.', '', '', '', ''),
('def/property/physiographic-feature-type', 'Physiographic feature type', '', 'specification of a kind of physiographic feature, e.g. mountain, continent, ocean, river, basin…', '', '', '', ''),
('def/property/pipe-extent', 'Pipe Extent', '', 'Total length in decimal format of the Drill pipe in the hole.', '', '', '', ''),
('def/property/plant-name', 'Plant Name', '', '', '', '', '', ''),
('def/property/plant-type', 'Plant Type', '', '', '', '', '', ''),
('def/property/point-of-contact', 'Point Of Contact', '', 'A responsible party identified as the agent to contact with respect to some resource', '', '', '', ''),
('def/property/pore-geometry-characteristics', 'Pore Geometry Characteristics', '', 'Property that describes the bulk characterisitcs of pore geometry in a rock, related to connectivity, throat diamter, surface physics of pore lining, etc.', '', '', '', ''),
('def/property/pore-scale-permeability', 'Pore-scale permeability', '', 'permeability measured on a small sample; unclear how this related to intrinisic permeability.', '', '', '', ''),
('def/property/porosity', 'porosity', '', ' a measure of the void (i.e. "empty") spaces in a material, reported as a fraction of the volume of voids over the total volume ', '', '', '', ''),
('def/property/postal-address', 'Postal Address', '', 'a fiat geographic position assigned to locate buildings or postal delivery locations.', '', '', '', ''),
('def/property/power', 'Power', '', '', '', '', '', ''),
('def/property/power-production-', 'power production ', '', 'prower produced by a facility during some time interval', '', '', '', ''),
('def/property/power-production-capacity', 'Power Production Capacity', '', 'Electrical power production capacity of a facility.', '', '', '', ''),
('def/property/precipitation-quantity', 'Precipitation Quantity', '', 'amount of rain (in length units over a unit area) over a specified length of time', '', '', '', ''),
('def/property/pressure', 'Pressure', '', '', '', '', '', ''),
('def/property/price', 'Price', '', 'The unit monetary value assigned to some thing', '', '', '', ''),
('def/property/procedure-description', 'Procedure Description', '', 'Free text for any notes pertaining to procedures', '', '', '', ''),
('def/property/procedure-name', 'Procedure Name', '', 'Text string for human designation of a procedure', '', '', '', ''),
('def/property/procedure-type', 'Procedure Type', '', 'Term that specifies the method used', '', '', '', ''),
('def/property/process-type', 'Process Type', '', '', '', '', '', ''),
('def/property/property-qualifier', 'property qualifier', '', 'specification of a modifier on a property value', '', '', '', ''),
('def/property/prospect-quality', 'prospect quality', '', 'property related to the evaluation of value of an earth resource, e.g. percent target rock, grade', '', '', '', ''),
('def/property/provenance', 'Provenance', '', 'description of the provenance of a resource', '', '', '', ''),
('def/property/publication-date', 'Publication Date', '', 'Date on which data for the borehole was or will be made public. Day, month and year must be specified; Excel will display using ISO 8601 date and time (yyyy-mm-ddT:hh:mm) format. If only the year is known, enter month and day as -Jan. 1-. If year is unknown, enter 1900. All dates will be converted to yyyy-mm-ddThh:mm. This is intended as a searching aid.', '', '', '', ''),
('def/property/purchaser', 'purchaser', '', 'specificaiton of the agent that buy some product ', '', '', '', ''),
('def/property/purpose', 'Purpose', '', 'the reason for which something is done', '', '', '', ''),
('def/property/quantifier', 'Quantifier', '', 'an expression that indicates the scope of a term to which it is atteched', '', '', '', ''),
('def/property/range-number', 'Range Number', '', 'A component of a PLSS location in the US.', '', '', '', ''),
('def/property/rank', 'rank', '', 'qualifier of the hierarchical level of some categorization', '', '', '', ''),
('def/property/recharge-extent', 'Recharge Extent', '', 'area to recharge mine void space', '', '', '', ''),
('def/property/reference-identifier', 'Reference Identifier', '', 'an identifier that is intended to be dereferenceable to link with another information item.', '', '', '', ''),
('def/property/related-resource', 'Related Resource', '', '', '', '', '', ''),
('def/property/relation', 'Relation', '', 'an association to another resource. The semantics of the relation should be specified in implementations', '', '', '', ''),
('def/property/relationship-type', 'relationship type', '', 'property specifying the relationship between one or more things.', '', '', '', ''),
('def/property/reporting-date', 'Reporting date', '', 'calendar date on which an associated property value was assigned and was current', '', '', '', ''),
('def/property/reporting-date/day', 'Reporting date/day', '', '', '', '', '', ''),
('def/property/reporting-date/month', 'Reporting date/month', '', '', '', '', '', ''),
('def/property/reporting-date/year', 'Reporting date/year', '', '', '', '', '', ''),
('def/property/reporting-time-of-day', 'Reporting time of day', '', 'Clock time of day (local time) when an observation was made', '', '', '', ''),
('def/property/representation', 'Representation', '', '', '', '', '', ''),
('def/property/residence-time', 'Residence Time', '', '', '', '', '', ''),
('def/property/resistivity', 'Resistivity', '', 'a measure of the resisting power of a specified material to the flow of an electric current.', '', '', '', ''),
('def/property/resource-assessment', 'Resource Assessment', '', '', '', '', '', ''),
('def/property/resource-history', 'Resource History', '', 'Description of the sequence of events leading to the current state of a resource', '', '', '', ''),
('def/property/resource-link', 'Resource Link', '', '', '', '', '', ''),
('def/property/resource-owner', 'Resource Owner', '', 'Companies, individuals, or other entities who own the property. Separate multiple with a pipe -|- character.', '', '', '', ''),
('def/property/resource-reference', 'Resource Reference', '', 'identifier for a resource; indended for machine designation of a feature. Generic reference, may be a numeric foreign key, or a short citation string, or a URI', '', '', '', ''),
('def/property/resource-responsible-party', 'Resource Responsible Party', '', 'Free text specification of party that originally registered sample; may be name or organization, with or without contact information.', '', '', '', ''),
('def/property/resource-state', 'Resource State', '', '', '', '', '', ''),
('def/property/resource-use-restriction', 'Resource Use Restriction', '', '', '', '', '', ''),
('def/property/resource-feature-name', 'Resource feature name', 'gravity', 'the name of a geologic feature identified as the source of some economically useful resource', '', '', '', ''),
('def/property/responsible-party', 'Responsible party', '', 'property that specifies an agent with some role relative to a resource, might include contact inforamation as well as name', '', '', '', ''),
('def/property/salinity', 'Salinity', '', 'measure of quantity of salt in a solution', '', '', '', ''),
('def/property/sample-type', 'Sample Type', '', 'Term classifying the sample type', '', '', '', ''),
('def/property/sampling-feature-identifier', 'Sampling Feature Identifier', '', 'Unique identifier for a  sampling feature; indended for machine designation of the feature', '', '', '', ''),
('def/property/sampling-survey-area', 'Sampling survey area', '', 'property of a survey design, specifies  the area of each sampling cell surveyed; geometry of the sampling cel not specified.', '', '', '', ''),
('def/property/sea-bottom-temperature', 'Sea bottom temperature', 'temperature, sea bottom | temperature, ocean bottom', 'temperature of the ocean measured at the bottom/sea floor at some location', '', '', '', ''),
('def/property/sea-surface-temperature', 'Sea surface temperature', 'SST | temperature, sea-surface | temperature, ocean surface', 'temperature of the ocean measured at the surface at some location', '', '', '', ''),
('def/property/section-number', 'Section Number', '', 'A component of a PLSS location, which is a fiat geographic area', '', '', '', ''),
('def/property/section-part', 'Section Part', '', 'specification of a sub region within a section area.  A component of a PLSS location, which is a fiat geographic area', '', '', '', ''),
('def/property/sedimentary-rock-cement', 'Sedimentary Rock Cement', '', '', '', '', '', ''),
('def/property/seismic-magnitude', 'Seismic Magnitude', '', 'A number that characterizes the relative size of an earthquake', '', '', '', ''),
('def/property/self-identifier', 'Self Identifier', '', 'a property whose value is intended to uniquely identify the containing dataObject instance, with a value assigned by the data manager', '', '', '', ''),
('def/property/severity-of-bleaching', 'Severity of Bleaching', '', 'property quantifies the severity of bleaching (as opposed to the extent of bleaching)', '', '', '', ''),
('def/property/shape', 'Shape', '', 'Specification of a geometry using Earth-referenced coordinates (e.g. location); must have an associated spatial reference system that specifies how coordinate values are mapped to the Earth. As a point, line, polygon or 3D geometry.', '', '', '', ''),
('def/property/source-citation', 'Source Citation', '', 'information that uniquely identifies the source of some thing', '', '', '', ''),
('def/property/source-identifier', 'Source Identifier', '', 'Unique identifier for a source; indended for machine designation of the feature. A referece constructed using a known identifier scheme (a URI)', '', '', '', ''),
('def/property/spacing', 'Spacing', '', 'a property that specifies the distance between objects in some aggregation', '', '', '', ''),
('def/property/spatial-reference-system', 'Spatial Reference System', '', 'defines a specific map projection', '', '', '', ''),
('def/property/specific-heat', 'Specific Heat', '', 'Estimated specific heat of water at the estimated air temperature', '', '', '', ''),
('def/property/specific-storage', 'specific storage', '', 'volume of fluid a geologic reservoir releases from or takes into storage per unit surface area of the reservoir per unit change in head. ', '', '', '', ''),
('def/property/specific-yield', 'specific yield', '', 'The ratio of the volume of fluid that a given mass of saturated rock or soil will yield by gravity to the volume of that mass.', '', '', '', ''),
('def/property/statistics-aggregation-type', 'Statistics aggregation type', '', 'method used to aggregate or measure quality results for measured values, e.g. average, area statisitcs', '', '', '', ''),
('def/property/status', 'Status', '', '', '', '', '', ''),
('def/property/status-date', 'Status Date', '', '', '', '', '', ''),
('def/property/substance-of-interest', 'Substance of Interest', '', '', '', '', '', ''),
('def/property/surface-chlorophyll-a-density', 'Surface chlorophyll a density', '', '', '', '', '', ''),
('def/property/taxa-present', 'Taxa present', '', 'categorization of the species, genus, family etc of the organisms present at some observation location', '', '', '', ''),
('def/property/telephone-number', 'Telephone Number', '', 'designation of a telephone network endpoint', '', '', '', ''),
('def/property/temperature', 'Temperature', '', 'the degree or intensity of heat present', '', '', '', ''),
('def/property/temperature-gradient', 'Temperature Gradient', '', 'Gradient determined from initial temperatures', '', '', '', ''),
('def/property/temporal-extent', 'Temporal extent', '', 'the time interval (relative to some Temporal reference system) during which a described event occurred', '', '', '', ''),
('def/property/thermal-conductivity', 'Thermal Conductivity', '', 'measurement of the ability of a material to conduct heat', '', '', '', ''),
('def/property/thermal-conductivity-correction', 'Thermal Conductivity Correction', '', 'Correction applied to thermal conductivity for in situ conditions.', '', '', '', ''),
('def/property/thermal-diffusivity', 'Thermal Diffusivity', '', 'How rapidly a material changes temperature to match the surroundings - equilibrium.', '', '', '', ''),
('def/property/thickness', 'Thickness', '', '', '', '', 'Atmosphere state', ''),
('def/property/time-interval', 'time interval', '', 'like duration, but interval of time between events', '', '', '', ''),
('def/property/time-position', 'Time Position', '', 'Numerical value for the age', '', '', '', ''),
('def/property/township-number', 'Township Number', '', 'A component of a PLSS location in the US.', '', '', '', ''),
('def/property/uncertainty', 'Uncertainty', '', '', '', '', '', ''),
('def/property/unit-of-measure', 'Unit of Measure', '', 'A quantity used as a standard of measurement', '', '', '', ''),
('def/property/update-time-stamp', 'Update Time Stamp', '', '', '', '', '', ''),
('def/property/us-cadastral-location', 'US Cadastral Location', '', '', '', '', '', ''),
('def/property/use-application', 'Use Application', 'utilization | usage', 'Explanation of how a resource is used', '', '', '', ''),
('def/property/use-limitation', 'Use limitation', '', 'specification of any legal or security constraints on the utilization of a resource.', '', '', '', ''),
('def/property/utilization', 'Utilization', '', 'Explanation of how a resource is used', '', '', '', ''),
('def/property/utm-easting', 'UTM Easting', '', '', '', '', '', ''),
('def/property/utm-northing', 'UTM Northing', '', '', '', '', '', ''),
('def/property/value', 'Value', '', 'a property of a variable that quantifies its value in some context', '', '', '', ''),
('def/property/variable-type', 'Variable Type', '', 'Term classifying the variable', '', '', '', ''),
('def/property/velocity-magnitude', 'Velocity Magnitude', '', 'the magnitude of the rate of change in location of some thing.', '', '', '', ''),
('def/property/vertical-datum', 'Vertical Datum', '', 'The point of reference against which elevation measurements are made. Best practice: use mean sea level (MSL) as datum.', '', '', '', ''),
('def/property/vertical-extent', 'Vertical Extent', '', 'A region between two elevations relative to some datum', '', '', '', ''),
('def/property/vertical-position', 'Vertical Position', '', 'A point location that is referenced above or below some horizontal datum', '', '', '', ''),
('def/property/viscosity', 'Viscosity', '', 'The viscosity of the drilling fluid; resistance to flow.', '', '', '', ''),
('def/property/voice-telephone', 'Voice Telephone', '', '', '', '', '', ''),
('def/property/volume', 'Volume', '', 'a measure of a quantity of space in three dimensions', '', '', 'Atmosphere state', 'need to harmonize labels with csdms naming conventions; phenomenon is velocity, subject is fluid flow in  atmosphere.'),
('def/property/volume-fluid-flux', 'Volume fluid flux', '', 'the mass of fluid that passes through a unit area per unit time', '', '', '', ''),
('def/property/water-depth', 'Water depth', '', 'depth of water to the measurement location or to the observed phenomon', '', '', '', ''),
('def/property/weight', 'Weight', '', '', '', '', '', ''),
('def/property/wind-velocity-magnitude', 'Wind velocity magnitude', 'wind speed', 'magnitude of the velocity of flowing air in the atmosphere (wind)', '', '', '', ''),
('def/property/x-coordinate', 'X coordinate', '', '', '', '', '', ''),
('def/property/y-coordinate', 'Y Coordinate', '', '', '', '', '', ''),
('def/property/younger-age', 'Younger Age', '', 'The younger bound for the age of the origin of a feature.', '', '', '', ''),
('def/property/postal-code', 'postal code', '', 'zip code or other similar code used to identify postal areas', '', '', '', ''),
('def/property/trap', 'trap', '', 'specification of the feature that allows a geologic reservoir to contain fluid without loss', '', '', '', ''),
('def/property/fluid-saturation', 'fluid saturation', '', 'fraction of available pore volume that is filled with  fluid', '', '', '', ''),
('def/property/total-dissolved-solids', 'total dissolved solids', '', 'mass per volume of dissolved salts in an aqueous solution', '', '', '', ''),
('def/property/gravity-corrected-observation', 'gravity corrected observation', '', '', '', '', '', ''),
('def/property/reservoir-drive-mechanism', 'reservoir drive mechanism', '', 'The mechanism that creates a pressure gradient to moves fluid in a subsurface reservoir  towards a wellbore as fluid is removed near the wellbore. ', '', '', '', ''),
('def/property/energy-consumption', 'energy consumption', '', 'amount of energy used by a facility over some period of time', '', '', '', ''),
('def/property/is-faulted', 'is faulted', '', 'boolean property indicating whether a feature is cut by geologic faults', '', '', '', ''),
('def/property/hydraulic-character', 'hydraulic character', '', 'property that specifies the degree to which water or other fluids can move through a material or structural feature.', '', '', '', ''),
('def/property/formation-factor', 'formation factor', '', 'The ratio of the resistivity of a rock filled with water (Ro) to the resistivity of that water (Rw).', '', '', '', ''),
('def/property/setting', 'setting', '', 'the place or type of surroundings where something is positioned or where an event takes place (Google)', '', '', '', ''),
('def/property/geologic-setting', 'geologic setting', '', 'the place or type of surroundings where something is positioned or where an event takes place, characterized in terms of geologic or tectonic properties.', '', '', '', ''),
('def/property/lithology', 'lithology', '', 'property that characterizes an earth material in some context', '', '', '', ''),
('def/property/load-factor', 'load factor', '', 'ratio of current energy input or output to the maximum recorded input or maximum output capacity.', '', '', '', '');
